app/urls.py
from django.urls import path
from app.views import *
app_name='app'
urlpatterns = [
    path('che/',che,name='che'),
]

app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns = [
    path('siddhu/',siddhu,name='siddhu'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns = [
    path('genaral/',genaral,name='genaral'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def che(request):
    return render(request,'che.html')

app1/views.py
from django.shortcuts import render

# Create your views here.def siddhu(request):
def siddhu(request):
    return render(request,'siddhu.html')

app2/views.py
from django.shortcuts import render

# Create your views here.def siddhu(request):
def genaral(request):
    return render(request,'genaral.html')

templates/che.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
<body>
	<h1>Hello how are you doing??</h1>
    <a href="{% url 'app1:siddhu' %}"><h1>I would like to know more about you</h1></a>
</body>
</html>

templates/genaral.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
<body>
	<h1>To get close to me be nice</h1>
</body>
</html>

templates/siddhu.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
<body>
	<h1>This is siddhu</h1>
    <a href="{% url 'app:che' %}"><h1>Click here to go back</h1></a>
</body>
</html>